services:
#    dash_taches.example:
#        class: Dash\TachesBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    dash_taches.task_creator:
        class: Dash\TachesBundle\TaskCreator\TaskCreator 

   