<?php

namespace Dash\CoreBundle\Repository;

/**
 * OjectifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectifRepository extends \Doctrine\ORM\EntityRepository
{
    public function findObjectif()
    {
        $qb = $this->createQueryBuilder('o');
        $qb->Where('o.moment BETWEEN :start AND :end')
            ->setParameter('start', new \Datetime(date('Y-M').'-01'))
            ->setParameter('end', new \Datetime(date('Y-M').'-31'))
            ;
        return $qb->getQuery()->getOneOrNullResult();
    }
}
