<?php

namespace Dash\DventeBundle\Repository;

/**
 * RchequeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RchequeRepository extends \Doctrine\ORM\EntityRepository
{
}
